export const PRIME_DETAIL_ROOT = '[data-testid="DVWebNode-detail-wrapper"]'
export const PRIME_MAIN_ROOT = 'main[data-testid="detailpage-main"]'
export const PRIME_SEASON_SELECTOR = '[data-testid="dp-season-selector"]'
export const PRIME_SEASON_LINK = '[data-testid="dp-season-selector"] a[href*="/detail/"]'
export const PRIME_EPISODE_ROW = 'li[data-testid="episode-list-item"]'
export const PRIME_EPISODE_PLAY = 'a[data-testid="episodes-playbutton"][role="button"]'
export const PRIME_MAIN_PLAY = 'a[data-testid="dp-atf-play-button"][role="button"]'
export const PRIME_PLAYER = '#dv-web-player'
export const PRIME_PLAYER_SURFACE = 'div[aria-label="Web Player"]'
export const PRIME_LOADING = '.atvwebplayersdk-loading-overlay[role="status"]'
export const PRIME_PLAYER_TITLE = '.atvwebplayersdk-title-text'
export const PRIME_PLAYER_EPISODE_INFO = '.atvwebplayersdk-episode-info'
export const PRIME_PLAYER_TIMING = '.atvwebplayersdk-episode-timing-container'
